Repository AgentOps-AI/agentops, pull requests merged in 2024-12, with the labels that each got.

#561 deps: remove `packaging`; unpinned & ranged versioning
  pyproject.toml
Labels: blocker, critical

#558 [Docs] Update and clean existing docs for better readability
  docs/images/external/ai21/ai21-session.png
  docs/images/external/anthropic/anthropic_icon_ivory.png
  docs/images/external/anthropic/anthropic_icon_slate.png
  docs/images/external/anthropic/anthropic_wordmark_ivory.png
  docs/images/external/anthropic/anthropic_wordmark_slate.png
  docs/images/external/cohere/Cohere-Logo-Color-RGB.png
  docs/images/external/cohere/Cohere-Logo-Mono Marble White-RGB.png
  docs/images/external/cohere/Cohere-Logo-Mono Volcanic Black-RGB.png
  docs/images/external/groq/groq_session.png
  docs/images/external/mistral/mistral-ai-icon.png
  docs/images/external/mistral/mistral_session.png
  docs/mint.json
  docs/v1/examples/examples.mdx
  docs/v1/examples/langchain.mdx
  docs/v1/examples/multi_session.mdx
  docs/v1/examples/multion.mdx
  docs/v1/examples/restapi.mdx
  docs/v1/integrations/ai21.mdx
  docs/v1/integrations/anthropic.mdx
  docs/v1/integrations/autogen.mdx
  docs/v1/integrations/cohere.mdx
  docs/v1/integrations/crewai.mdx
  docs/v1/integrations/groq.mdx
  docs/v1/integrations/langchain.mdx
  docs/v1/integrations/litellm.mdx
  docs/v1/integrations/mistral.mdx
  docs/v1/integrations/multion.mdx
  docs/v1/integrations/ollama.mdx
  docs/v1/integrations/openai.mdx
  docs/v1/introduction.mdx
  docs/v1/quickstart.mdx
  docs/v1/usage/advanced-configuration.mdx
  docs/v1/usage/dashboard-info.mdx
  docs/v1/usage/langchain-callback-handler.mdx
  docs/v1/usage/recording-events.mdx
  docs/v1/usage/sdk-reference.mdx
  docs/v1/usage/tracking-agents.mdx
  docs/v1/usage/tracking-llm-calls.mdx
  examples/anthropic_examples/README.md
  examples/anthropic_examples/agentops-anthropic-understanding-tools.ipynb
  examples/anthropic_examples/anthropic-example-sync.ipynb
  examples/anthropic_examples/anthropic_example.ipynb
  examples/anthropic_examples/antrophic-example-tool.ipynb
  examples/multi_session_llm.ipynb
  examples/openai_examples/openai_example_async.ipynb
Labels: documentation

#563 [FEAT] Integrate xAI
  docs/images/external/xai/xai-logo.png
  docs/mint.json
  docs/v1/examples/examples.mdx
  docs/v1/integrations/xai.mdx
  examples/xai_examples/grok_examples.ipynb
  examples/xai_examples/grok_vision_examples.ipynb
Labels: enhancement

#586 [Fix] Remove author name from stale check CI
  .github/workflows/stale-check.yml
Labels: ci

#585 [Fix] Updated notebooks that publish to examples docs pages
  docs/v1/examples/camel.mdx
  docs/v1/examples/examples.mdx
  docs/v1/examples/langchain.mdx
  docs/v1/examples/simple_agent.mdx
  docs/v1/integrations/camel.mdx
  examples/anthropic_examples/README.md
  examples/anthropic_examples/agentops-anthropic-understanding-tools.ipynb
  examples/anthropic_examples/anthropic-example-async.ipynb
  examples/anthropic_examples/anthropic-example-sync.ipynb
  examples/anthropic_examples/antrophic-example-tool.ipynb
  examples/camel_examples/README.md
  examples/camel_examples/bladewolf_training.csv
  examples/camel_examples/camel_example.ipynb
  examples/camel_examples/camelai-multi-agent-example.ipynb
  examples/camel_examples/camelai-simple-example.ipynb
  examples/camel_examples/camelai-simple-examples.ipynb
  examples/langchain_examples/langchain_examples.ipynb
  examples/langchain_examples/langchain_v0_example.ipynb
  examples/multion_examples/Autonomous_web_browsing.ipynb
  examples/xai_examples/grok_vision_examples.ipynb
Labels: documentation

#541 [FEAT] TaskWeaver Integration
  agentops/llms/providers/taskweaver.py
  agentops/llms/tracker.py
  agentops/partners/taskweaver_event_handler.py
  docs/images/external/microsoft/microsoft_logo.svg
  docs/images/external/microsoft/taskweaver_logo.svg
  docs/images/external/microsoft/taskweaver_session.png
  docs/mint.json
  docs/v1/examples/examples.mdx
  docs/v1/integrations/taskweaver.mdx
Labels: enhancement
