Repository AgentOps-AI/agentops, pull requests merged in 2025-06, with the labels that each got.

#1058 Clean up v2 docs links
  docs/v1/concepts/core-concepts.mdx
  docs/v1/concepts/sessions.mdx
  docs/v1/usage/advanced-configuration.mdx
  docs/v1/usage/langchain-callback-handler.mdx
  docs/v1/usage/multiple-sessions.mdx
  docs/v1/usage/sdk-reference.mdx
  docs/v1/usage/tracking-llm-calls.mdx
  docs/v2/integrations/langchain.mdx
  docs/v2/introduction.mdx
  docs/v2/usage/advanced-configuration.mdx
Labels: codex

#1059 fix: Productionize github action to add notebooks
  .github/workflows/add-notebook-examples-to-docs.yml
Labels: enhancement, ci

#1060 Fix docs env config parameters
  docs/v1/usage/advanced-configuration.mdx
  docs/v2/concepts/host-env.mdx
  docs/v2/usage/advanced-configuration.mdx
Labels: codex

#1065 Fix xAI icon path
  docs/v2/introduction.mdx
Labels: codex

#1067 Fix CrewAI LLM docs
  docs/v2/integrations/crewai.mdx
Labels: codex

#1089 fix: Sync with the latest example notebooks
  docs/v2/examples/autogen.mdx
  docs/v2/examples/examples.mdx
  docs/v2/examples/google_adk.mdx
  docs/v2/examples/google_genai.mdx
  docs/v2/examples/google_generative_ai.mdx
  docs/v2/examples/langchain.mdx
  docs/v2/examples/litellm.mdx
  docs/v2/examples/mem0.mdx
  docs/v2/examples/openai.mdx
  docs/v2/examples/openai_agents.mdx
  docs/v2/examples/smolagents.mdx
  docs/v2/examples/xai.mdx
  examples/autogen/AgentChat.ipynb
  examples/smolagents/multi_smolagents_system.ipynb
  examples/xai/grok_examples.ipynb
Labels: documentation

#1080 Add separate docs for OpenAI Agents SDKs
  README.md
  docs/mint.json
  docs/v2/integrations/openai_agents_js.mdx
  docs/v2/integrations/openai_agents_python.mdx
  docs/v2/introduction.mdx
Labels: codex

#1120 Limit span resource attributes
  agentops/instrumentation/common/token_counting.py
  agentops/sdk/attributes.py
  agentops/sdk/core.py
  tests/unit/instrumentation/common/test_token_counting.py
  tests/unit/sdk/test_resource_attributes.py
Labels: codex
