Repository AgentOps-AI/agentops, pull requests merged in 2025-01, with the labels that each got.

#622 [Feat] Integrate HugginFace `smolagents` into docs
  docs/images/external/huggingface/hf-logo.png
  docs/mint.json
  docs/v1/examples/examples.mdx
  docs/v1/integrations/smolagents.mdx
  examples/smolagents_examples/multi_smolagents_system.ipynb
  examples/smolagents_examples/text_to_sql.ipynb
Labels: documentation

#609 [Feat] OpenAI Assistants (Beta) Integration
  agentops/llms/providers/openai.py
  agentops/llms/tracker.py
  docs/v1/examples/examples.mdx
  docs/v1/examples/openai_assistants.mdx
  docs/v1/integrations/openai.mdx
  examples/openai_examples/images/assistants_overview_assistants_dashboard.png
  examples/openai_examples/images/assistants_overview_assistants_playground.png
  examples/openai_examples/images/assistants_overview_diagram.png
  examples/openai_examples/images/assistants_overview_enable_code_interpreter.png
  examples/openai_examples/images/assistants_overview_enable_function.png
  examples/openai_examples/images/assistants_overview_enable_retrieval.png
  examples/openai_examples/images/assistants_overview_new_assistant.png
  examples/openai_examples/language_models_are_unsupervised_multitask_learners.pdf
  examples/openai_examples/openai_assistants_example.ipynb
  tests/core_manual_tests/providers/openai_assistants_canary.py
Labels: enhancement

#602 Update AG2 Reference
  CONTRIBUTING.md
  README.md
  docs/images/external/autogen/ag2_blue.svg
  docs/v1/examples/examples.mdx
  docs/v1/integrations/autogen.mdx
  docs/v1/usage/sdk-reference.mdx
  examples/README.md
  examples/autogen_examples/AgentChat.ipynb
  examples/autogen_examples/MathAgent.ipynb
  examples/demos/agentchat_agentops.ipynb
Labels: documentation

#635 [Fix] autogen action events logging
  agentops/partners/autogen_logger.py
  examples/autogen_examples/MathAgent.ipynb
Labels: bug

#645 Rename InstrumentedProvider to BaseProvider
  CONTRIBUTING.md
  agentops/llms/providers/ai21.py
  agentops/llms/providers/anthropic.py
  agentops/llms/providers/base.py
  agentops/llms/providers/cohere.py
  agentops/llms/providers/groq.py
  agentops/llms/providers/litellm.py
  agentops/llms/providers/llama_stack_client.py
  agentops/llms/providers/mistral.py
  agentops/llms/providers/ollama.py
  agentops/llms/providers/openai.py
  agentops/llms/providers/taskweaver.py
Labels: v0.4

#646 Refactored `ErrorEvent` to inherit from `Event` class
  agentops/event.py
Labels: v0.4

#661 Set file logging to false by default
  agentops/log_config.py
Labels: help wanted, opinion
